sudo: required
language: minimal

services:
  - docker

before_install:
  - ./.travis/install_docker.sh

before_script:
  - docker-compose -f docker-compose.travis.yml build app
script:
  - docker-compose -f docker-compose.travis.yml run app pytest -vv -n 3 --cov={bot,core}
after_script:
  - docker-compose -f docker-compose.travis.yml down

deploy:
  provider: heroku
  api_key:
    secure: RVFbkZ17sMcl0NmleKYEE1Sd8cMsP3OsH3n3FiPSh/ZAH+W8VnGw86auaHidn4qIc7jXFRQ64UmuFG1dWmQVPpj7wuNVBwginH1RQ4nb0TTIT5xbBIQjNTUnLAvmCNTnRRiuUuAfmC31OTVlN417eFmKA10kT93MqEkHsPonot0tAbcmGgsZgscwadxGJf/qnZaM8f3o440qaD8Jy4CGap28wkTr+V2wW8St6bZllBX4fGKrKstOquYSsBnnjTJJpBUHy5p7Ql88n+DWfZFIEFz1uejcVZ+LqHmJEsHfvUkskN2GBzWprO5GimnEhDHHp3T/iOF2OYEWoReWuDFCFkTWnFO58NaZnvl5JpDvIWZ0zduFMdZxhM5sJkMawDKvm03WDq6whILxEAo4EWuWm16JhE4cF8zmiCHkyiPYqJyM2+VEeZ1TFEeXEL7DP1KI5zesWPi+chz5AL8q4Q7ji3f58tzYWwTl0TC9d8lwTxrCs/FjZwIaBVUV+JeUaZWUhH7EcZYd2HmVYL1Z1XSEfTp4S4fQ5Q8P6qBUy1p07M4yG3oBkGjgAeHFpNip9cUCnUhfcnL87+GaufyB8pR0lRbBygJxmJf8asKOkaGYCqMk4iJvqTg+KRHyb3uqLL2Bj1QWOdirtkv100jowrwA7AjXoytGK2zyEJBxe/K7JPo=
  app:
    master: tgreactor
